apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: erdialtnsk/quotes-back:v2
        env:
        - name: SQLALCHEMY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: SQLALCHEMY_DATABASE_URI
        ports:
        - containerPort: 3000