apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: data
  name: data-deployment
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: data
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: data
    spec:
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: data-pvc
      containers:
      - envFrom:
        - secretRef:
            name: data-secret
        image: erdialtnsk/quotes-data:v1
        name: db
        ports:
        - containerPort: 3306
        resources: {}
        args:
        - "--ignore-db-dir=lost+found"
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: data-vol
      restartPolicy: Always
status: {}

