apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
